# dependency on: ansible-galaxy collection install community.crypto
# needs PyOpenSSL or cryptogrphy
#
# set to force:no so that once a key/cert pair is created, we don't overwrite
#
---

- name: custom CA certificate authority
  import_tasks: ca.yml

- name: create certificate for primary ingress
  import_tasks: generate-cert.yml
