---

- hosts: localhost
  become: no
  gather_facts: no
  connection: local

  tasks:

    - name: call script to delete GCP external load balancer
      command:
        cmd: ./delete-https-lb.sh ext {{network_name}} {{lb_subnet_name}} {{region}} {{cert_domains_list|first}}
        chdir: "{{playbook_dir}}/../gcloud"
      register: lb_res
    - debug: msg="{{lb_res}}"

    - name: call script to delete GCP internal load balancer
      command:
        cmd: ./delete-https-lb.sh int {{network_name}} {{lb_subnet_name}} {{region}} {{cert_domains_list|first}}
        chdir: "{{playbook_dir}}/../gcloud"
      register: lb_res
    - debug: msg="{{lb_res}}"

    - set_fact:
        only_instance_groups: 1

    - name: call script to delete backing instance groups
      command:
        cmd: ./delete-https-lb.sh int {{network_name}} {{lb_subnet_name}} {{region}} {{cert_domains_list|first}} {{only_instance_groups}}
        chdir: "{{playbook_dir}}/../gcloud"
      register: lb_res
    - debug: msg="{{lb_res}}"
